[project]
name = "uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.2",
    "joblib>=1.5.2",
    "numpy>=2.3.4",
    "pydantic>=2.12.4",
    "scikit-learn>=1.7.2",
    "uvicorn[standard]>=0.38.0",
]
